services:
    backend:
        image: ghcr.io/astral-sh/uv:0.6.5-bookworm
        working_dir: /app
        volumes:
            - ./:/app/:ro
        entrypoint:
            - ./scripts/backend.sh
        command:
            - run
        ports:
            - 8500:8500

    frontend:
        image: docker.io/node:23.9-bookworm-slim
        working_dir: /app
        volumes:
            - ./:/app/
        entrypoint:
            - ./scripts/frontend.sh
        command:
            - run
        ports:
            - 8300:8300
