services:
  backend-server:
    image: ghcr.io/astral-sh/uv:0.6.5-bookworm
    environment:
      - UV_CACHE_DIR=./env/uv/cache
      - UV_PYTHON_INSTALL_DIR=./env/uv/python
    working_dir: /app
    volumes:
      - ./:/app/
    entrypoint:
      - ./run.sh
    command: ['run']
    ports:
      - 8250:8250

  frontend-install:
    image: docker.io/node:23.9-bookworm-slim
    working_dir: /app
    volumes:
      - ./:/app/
    entrypoint:
      - npm
      - --prefix
      - /app/bond/frontend
    command:
      - install
  frontend-watch:
    extends:
      service: frontend-install
    command:
      - run
      - watch
    depends_on:
      frontend-install:
        condition: service_completed_successfully
