# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ApiRequest(betterproto.Message):
    """Request message from the client"""

    text: str = betterproto.string_field(1)


@dataclass
class ApiResponse(betterproto.Message):
    """Response message from the server (streamed)"""

    cell_id: str = betterproto.string_field(1)
    stream_id: str = betterproto.string_field(2)
    payload: str = betterproto.string_field(3)
